In [1]:
from IPython.display import HTML
import numpy as np
import pandas as pd
import matplotlib
import matplotlib.pyplot as plt
from sklearn.tree import DecisionTreeRegressor
from sklearn.model_selection import train_test_split
from sklearn import tree
from sklearn.metrics import precision_score
    
%matplotlib inline
import seaborn as sns

In [2]:
#read in the data
data = pd.read_csv('AggredgatedData.csv', sep=',', na_values=[" ", ""], index_col=0)

In [3]:
features = list(data.columns[1:-1])
X = data[features]
Y = data['2016ODabovenatavg']

X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.33, random_state=1)

##I. Model Selection Using Grid Search 

This is a useful tool to see which Classifier yields the highest accuracy.

In [37]:
from sklearn.model_selection import GridSearchCV
from sklearn.pipeline import Pipeline

In [98]:
# Create a pipeline
pipe = Pipeline([('classifier', RandomForestClassifier())])

# Create space of candidate learning algorithms and their hyperparameters
search_space = [{'classifier': [LogisticRegression()],
                 'classifier__penalty': ['l1', 'l2'],
                 'classifier__C': [0.01, 1, 100]},
                {'classifier': [RandomForestClassifier()],
                 'classifier__n_estimators': [10, 50, 60, 100],
                 'classifier__criterion': ['gini', 'entropy'],
                 'classifier__max_features': [1, 2, 3],
                 'classifier__oob_score': [True],
                },
                {'classifier': [SGDClassifier()],
                 'classifier__penalty': ['l1', 'l2'],
                 'classifier__loss': ['hinge', 'log', 'modified_huber'],
                 },
                {'classifier': [SVC()],
                 'classifier__kernel': ['linear', 'rbf', 'sigmoid'],
                 'classifier__C': [1, 10],
                 'classifier__gamma': [0.01, 1, 10, 100]} ]

clf0 = GridSearchCV(pipe, search_space, cv=5, verbose=0)
best_model = clf0.fit(X_train, Y_train)
# View best model
best_model.best_estimator_.get_params()['classifier']

//anaconda/lib/python2.7/site-packages/sklearn/ensemble/forest.py:453: UserWarning: Some inputs do not have OOB scores. This probably means too few trees were used to compute any reliable oob estimates.
  warn("Some inputs do not have OOB scores. "


RandomForestClassifier(bootstrap=True, class_weight=None, criterion='entropy',
            max_depth=None, max_features=3, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=1000, n_jobs=1,
            oob_score=True, random_state=None, verbose=0, warm_start=False)

In [99]:
best_model.predict(X_test)

array([False, False, False, False, False, False,  True, False, False,
       False,  True,  True,  True, False,  True, False, False,  True,
       False, False,  True, False, False,  True, False, False, False,
        True,  True, False, False, False,  True, False,  True, False,
        True, False,  True,  True, False, False, False, False,  True,
        True, False, False, False, False, False,  True, False], dtype=bool)

In [100]:
best_model.score(X_test, Y_test)

0.83018867924528306

##II. SVM

Pros: 
* Effective in high dimensional spaces.
* Still effective in cases where number of dimensions is greater than the number of samples.
* Uses a subset of training points in the decision function (called support vectors), so it is also memory efficient.
* Versatile: different Kernel functions can be specified for the decision function. Common kernels are provided, but it is also possible to specify custom kernels.

Cons:

* If the number of features is much greater than the number of samples, avoid over-fitting in choosing Kernel functions and regularization term is crucial.
* SVMs do not directly provide probability estimates, these are calculated using an expensive five-fold cross-validation

##Cross Validation

Learning the parameters of a prediction function and testing it on the same data is a methodological mistake: a model that would just repeat the labels of the samples that it has just seen would have a perfect score but would fail to predict anything useful on yet-unseen data. 

This situation is called overfitting. 

To avoid it, it is common practice when performing a (supervised) machine learning experiment to hold out part of the available data as a test set X_test, y_test. 

When evaluating different settings (“hyperparameters”) for estimators, such as the C setting that must be manually set for an SVM, there is still a risk of overfitting on the test set because the parameters can be tweaked until the estimator performs optimally. 

This way, knowledge about the test set can “leak” into the model and evaluation metrics no longer report on generalization performance. 

To solve this problem, yet another part of the dataset can be held out as a so-called “validation set”: training proceeds on the training set, after which evaluation is done on the validation set, and when the experiment seems to be successful, final evaluation can be done on the test set.

However, by partitioning the available data into three sets, we drastically reduce the number of samples which can be used for learning the model, and the results can depend on a particular random choice for the pair of (train, validation) sets.

A solution to this problem is a procedure called cross-validation (CV for short). A test set should still be held out for final evaluation, but the validation set is no longer needed when doing CV. In the basic approach, called k-fold CV, the training set is split into k smaller sets (other approaches are described below, but generally follow the same principles). The following procedure is followed for each of the k “folds”:

    * A model is trained using k-1 of the folds as training data;
    * the resulting model is validated on the remaining part of the data (i.e., it is used as a test set to compute a performance measure such as accuracy).
    
The performance measure reported by k-fold cross-validation is then the average of the values computed in the loop. This approach can be computationally expensive, but does not waste too much data (as it is the case when fixing an arbitrary test set), which is a major advantage in problem such as inverse inference where the number of samples is very small.

In [4]:
from sklearn.svm import SVC
from sklearn.model_selection import cross_val_score

Linear kernel = Straight Line (hyperplane) as the decision boundary
* rarely used in practice

RBF = commonly used kernel in SVC
2 parameters:
* gamma
* C

Gamma:
*  'spread' of the kernel and therefore the decision region.
* low gamma -> the 'curve' of the decision boundary is very low and thus the decision region is very broad (underfitting)
* gamma = 10 (The decision boundary starts to be highly effected by individual data points (i.e. variance)).
* high gamma -> the 'curve' of the decision boundary is high, which creates islands of decision-boundaries around data points (overfitting)
* If gamma is ‘auto’ then 1/n_features will be used instead.

C:
* penalty for misclassifying a data point
* small C -> classifier is okay with misclassified data points (high bias, low variance)
* big C -> classifier is heavily penalized for misclassified data and therefore bends over backwards avoid any misclassified data points (low bias, high variance)

C > 10 is too slow

degree : int, optional (default=3)

* Degree of the polynomial kernel function (‘poly’). Ignored by all other kernels.

In [35]:
kernels = ['linear', 'rbf', 'sigmoid']

for i in kernels:
    for j, C in enumerate((0.01, 1, 10, 100)):
        for k, D in enumerate((1, 10)):
            clf = SVC(C=D, cache_size=200, class_weight=None, coef0=0.0,
                      decision_function_shape='ovr', degree=3, gamma=C, kernel=i,
                      max_iter=-1, probability=False, random_state=None, shrinking=True,
                      tol=0.001, verbose=False)
            clf.fit(X_train, Y_train) 
            scores = cross_val_score(clf, X, Y, cv = 10)

            print ("Kernel: %s | Gamma: %0.2f | C: %i" % (i, C, D))
            print scores
            print("Accuracy: %0.2f (+/- %0.2f)" % (scores.mean(), scores.std() * 2))

Kernel: linear | Gamma: 0.01 | C: 1
[ 0.70588235  0.6875      0.5         0.75        0.8125      0.5625      0.875
  0.625       0.8         0.8       ]
Accuracy: 0.71 (+/- 0.23)
Kernel: linear | Gamma: 0.01 | C: 10
[ 0.52941176  0.8125      0.5625      0.625       0.75        0.6875      0.875
  0.625       0.6         0.53333333]
Accuracy: 0.66 (+/- 0.23)
Kernel: linear | Gamma: 1.00 | C: 1
[ 0.70588235  0.6875      0.5         0.75        0.8125      0.5625      0.875
  0.625       0.8         0.8       ]
Accuracy: 0.71 (+/- 0.23)
Kernel: linear | Gamma: 1.00 | C: 10
[ 0.52941176  0.8125      0.5625      0.625       0.75        0.6875      0.875
  0.625       0.6         0.53333333]
Accuracy: 0.66 (+/- 0.23)
Kernel: linear | Gamma: 10.00 | C: 1
[ 0.70588235  0.6875      0.5         0.75        0.8125      0.5625      0.875
  0.625       0.8         0.8       ]
Accuracy: 0.71 (+/- 0.23)
Kernel: linear | Gamma: 10.00 | C: 10
[ 0.52941176  0.8125      0.5625      0.625       0.75     

### Ideal Model

Kernel: rbf | Gamma: 0.01 | C: 1

[ 0.76470588  0.6875      0.5625      0.6875      0.875       0.6875
  0.6875      0.6875      0.6         0.8       ]
  
Accuracy: 0.70 (+/- 0.17)

In [123]:
clf0 = SVC(C=1, cache_size=200, class_weight=None, coef0=0.0,
          decision_function_shape='ovr', degree=3, gamma=0.01, kernel='linear',
          max_iter=-1, probability=False, random_state=None, shrinking=True,
          tol=0.001, verbose=False)
clf0.fit(X_train, Y_train) 
scores = cross_val_score(clf0, X, Y, cv = 10)

In [124]:
print("Accuracy: %0.2f (+/- %0.2f)" % (scores.mean(), scores.std() * 2))

Accuracy: 0.71 (+/- 0.23)


In [125]:
clf0.coef_

array([[  2.63848801e-01,  -6.68540451e-02,   3.09387286e-01,
         -2.05750837e-01,   1.34634014e+00,   1.40482994e-01,
          7.49506633e-01,   1.59324072e+00,   3.68813954e-01,
          3.97217579e-02,  -3.60074262e-01,   1.83569736e-01,
         -2.72166587e-01,  -2.27081181e-01,   8.76271007e-03,
          3.60658592e-01,  -4.52500113e-01,  -2.06844360e-01,
          2.52252443e-02,   3.51946070e-01,  -8.41550902e-01,
          5.08848354e-01,  -2.47331720e-01,   7.35406646e-01,
         -1.60632132e-02,  -1.61889112e-01,   5.63491887e-01,
         -3.35239154e-01,   8.46799623e-04,   2.23128289e-01,
          5.84754921e-02,  -2.64266052e-01,   1.39304776e-01,
          1.76294694e-02,  -5.67709251e-02,  -7.26662105e-01,
          1.72026303e-03,  -1.46720138e-02,   5.96602027e-01,
          2.40489622e-03]])

In [126]:
clf0.intercept_

array([-1.91970688])

##II. Logistic Regression

* binary classifier

L1 regularization (also called least absolute deviations) 
* push feature coefficients to 0, creating a method for feature selection. 
* as C decreases, more coefficients become 0.

In [7]:
from sklearn.linear_model import LogisticRegression

In [86]:
clf1 = LogisticRegression(penalty='l1', dual=False, tol=0.01, C=100.0, fit_intercept=True, 
                   intercept_scaling=1, class_weight=None, random_state=None, solver='liblinear', 
                   max_iter=100, multi_class='ovr', verbose=0, warm_start=False, n_jobs=1)
clf1.fit(X_train, Y_train) 

print(clf1.predict(X_test))

[ True False False  True False  True  True False False  True  True False
  True False  True  True  True  True False False  True  True False False
 False False  True  True  True False  True False  True False  True False
  True False False False False False False False  True False  True False
  True False  True  True False]


In [87]:
scores = cross_val_score(clf1, X, Y, cv = 10)
print scores
print("Accuracy: %0.2f (+/- %0.2f)" % (scores.mean(), scores.std() * 2))

[ 0.64705882  0.6875      0.5         0.5         0.6875      0.6875      0.875
  0.5625      0.6         0.73333333]
Accuracy: 0.65 (+/- 0.22)


In [88]:
#Comparison of the sparsity (% of zero coefficients) of solutions when L1 and L2 penalty 
#are used for different values of C. 
#We can see that large values of C give more freedom to the model. 
#Conversely, smaller values of C constrain the model more. 
#In the L1 penalty case, this leads to sparser solutions.

for i, C in enumerate((100, 1, 0.01)):
    # turn down tolerance for short training time
    clf_l1_LR = LogisticRegression(C=C, penalty='l1', tol=0.01)
    clf_l2_LR = LogisticRegression(C=C, penalty='l2', tol=0.01)
    clf_l1_LR.fit(X, Y)
    clf_l2_LR.fit(X, Y)

    coef_l1_LR = clf_l1_LR.coef_.ravel()
    coef_l2_LR = clf_l2_LR.coef_.ravel()

    # coef_l1_LR contains zeros due to the
    # L1 sparsity inducing norm

    sparsity_l1_LR = np.mean(coef_l1_LR == 0) * 100
    sparsity_l2_LR = np.mean(coef_l2_LR == 0) * 100

    print("C=%.2f" % C)
    print("Sparsity with L1 penalty: %.2f%%" % sparsity_l1_LR)
    print("score with L1 penalty: %.4f" % clf_l1_LR.score(X, Y))
    print("Sparsity with L2 penalty: %.2f%%" % sparsity_l2_LR)
    print("score with L2 penalty: %.4f" % clf_l2_LR.score(X, Y))

C=100.00
Sparsity with L1 penalty: 5.00%
score with L1 penalty: 0.8491
Sparsity with L2 penalty: 0.00%
score with L2 penalty: 0.8491
C=1.00
Sparsity with L1 penalty: 57.50%
score with L1 penalty: 0.7736
Sparsity with L2 penalty: 0.00%
score with L2 penalty: 0.7925
C=0.01
Sparsity with L1 penalty: 95.00%
score with L1 penalty: 0.6415
Sparsity with L2 penalty: 0.00%
score with L2 penalty: 0.7421


## III. Stochastic Gradient Descent (SGD)

Pros:
* Efficiency.
* Ease of implementation (lots of opportunities for code tuning).

Cons:
* requires a number of hyperparameters such as the regularization parameter and the number of iterations.
* sensitive to feature scaling.

In [15]:
from sklearn.linear_model import SGDClassifier

In [89]:
clf3 = SGDClassifier(alpha=0.0001, average=False, class_weight=None, epsilon=0.1,
       eta0=0.0, fit_intercept=True, l1_ratio=0.15,
       learning_rate='optimal', loss='hinge', max_iter=None, n_iter=None,
       n_jobs=1, penalty='l2', power_t=0.5, random_state=None,
       shuffle=True, tol=None, verbose=0, warm_start=False)

clf3.fit(X_train, Y_train)

SGDClassifier(alpha=0.0001, average=False, class_weight=None, epsilon=0.1,
       eta0=0.0, fit_intercept=True, l1_ratio=0.15,
       learning_rate='optimal', loss='hinge', max_iter=None, n_iter=None,
       n_jobs=1, penalty='l2', power_t=0.5, random_state=None,
       shuffle=True, tol=None, verbose=0, warm_start=False)

In [90]:
clf3.predict(X_test)

array([ True, False, False, False, False, False, False, False, False,
        True,  True, False, False, False, False, False, False,  True,
       False, False, False, False, False, False, False,  True, False,
       False,  True, False,  True, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False], dtype=bool)

In [91]:
clf3.coef_

array([[ -5.23217789e+01,  -3.27011118e+01,  -2.61608895e+01,
         -2.61608895e+01,   8.50228908e+01,   5.88620013e+01,
          1.95828386e+02,   2.36071445e+02,   1.31615923e+02,
          1.14939664e+01,   1.12390395e+01,  -2.20715014e+00,
         -4.77775141e+01,  -4.15829428e+01,   3.31181442e+01,
          2.51492789e+01,  -2.71001948e+01,  -3.98133628e+01,
          5.95502310e+00,   2.28872008e+01,   4.94410705e+00,
          9.04832470e+00,   7.46644264e+00,   3.59557058e+01,
         -1.45118112e+01,  -5.14007471e+00,   3.04663837e+00,
         -1.71934843e+01,   4.97520380e+01,   4.02451916e+01,
          3.69608367e+01,  -1.71696321e+02,  -6.73574243e+01,
          4.06115108e-01,  -6.76913015e-01,  -3.44146501e+01,
         -1.75283087e-01,  -3.19077067e-01,   3.70045782e+01,
          6.77973026e-02]])

In [92]:
clf3.intercept_   

array([-42.41118979])

In [93]:
scores = cross_val_score(clf3, X, Y, cv = 10)
print scores
print("Accuracy: %0.2f (+/- %0.2f)" % (scores.mean(), scores.std() * 2))

[ 0.76470588  0.875       0.5         0.625       0.5625      0.5625      0.75
  0.75        0.66666667  0.66666667]
Accuracy: 0.67 (+/- 0.22)


##IV. Random Forest Classifier

A random forest is a meta estimator that fits a number of decision tree classifiers on various sub-samples of the dataset and use averaging to improve the predictive accuracy and control over-fitting. 

The sub-sample size is always the same as the original input sample size but the samples are drawn with replacement if bootstrap=True (default).

Pros:

* It runs efficiently on large data bases.
* It can handle thousands of input variables without variable deletion.
* It gives estimates of what variables are important in the classification.
* It generates an internal unbiased estimate of the generalization error as the forest building progresses.
* It has an effective method for estimating missing data and maintains accuracy when a large proportion of the data are missing.
* It has methods for balancing error in class population unbalanced data sets.
* Generated forests can be saved for future use on other data.
* Prototypes are computed that give information about the relation between the variables and the classification.
* It computes proximities between pairs of cases that can be used in clustering, locating outliers, or (by scaling) give interesting views of the data.
* The capabilities of the above can be extended to unlabeled data, leading to unsupervised clustering, data views and outlier detection.
* It offers an experimental method for detecting variable interactions.

## Number of Trees in RF


Random forests does not overfit. You can run as many trees as you want. It is fast. Running on a data set with 50,000 cases and 100 variables, it produced 100 trees in 11 minutes on a 800Mhz machine. For large data sets the major memory requirement is the storage of the data itself, and three integer arrays with the same dimensions as the data. If proximities are calculated, storage requirements grow as the number of cases times the number of trees.

In random forests, there is no need for cross-validation or a separate test set to get an unbiased estimate of the test set error. It is estimated internally, during the run, as follows:

Each tree is constructed using a different bootstrap sample from the original data. About one-third of the cases are left out of the bootstrap sample and not used in the construction of the kth tree.

* https://www.stat.berkeley.edu/~breiman/RandomForests/cc_home.htm#remarks

The RandomForestClassifier is trained using bootstrap aggregation, where each new tree is fit from a bootstrap sample of the training observations z_i = (x_i, y_i). 

The out-of-bag (OOB) error is the average error for each z_i calculated using predictions from the trees that do not contain z_i in their respective bootstrap sample. 

This allows the RandomForestClassifier to be fit and validated whilst being trained. 

* T. Hastie, R. Tibshirani and J. Friedman, “Elements of Statistical Learning Ed. 2”, p592-593, Springer, 2009.

In [71]:
from sklearn.ensemble import RandomForestClassifier

In [107]:
clf4 = RandomForestClassifier(n_estimators=50, criterion='entropy', max_depth=None, 
                              min_samples_split=2, 
                       min_samples_leaf=1, min_weight_fraction_leaf=0.0, 
                              max_features='auto', 
                       max_leaf_nodes=None, min_impurity_decrease=0.0, min_impurity_split=None, 
                       bootstrap=True, oob_score=True, n_jobs=1, random_state=None, verbose=0, 
                       warm_start=False, class_weight=None)
            
clf4.fit(X_train, Y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='entropy',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=50, n_jobs=1,
            oob_score=True, random_state=None, verbose=0, warm_start=False)

In [109]:
clf4.score(X_test, Y_test)

0.92452830188679247

##Figuring out ok counties

In [148]:
preds = clf4.predict(X) 
itemindex = np.where(preds==False)
ok_counties = data.ix[itemindex]
index_ok_counties = ok_counties.index.values

In [149]:
data2017 = pd.read_csv('AggregatedData2017.csv', sep=',', na_values=[" ", ""], index_col=0)
data2018 = pd.read_csv('AggregatedData2018.csv', sep=',', na_values=[" ", ""], index_col=0)

ok_counties_2017 = data2017.ix[index_ok_counties]
ok_counties_2018 = data2018.ix[index_ok_counties]

In [153]:
features = list(ok_counties_2017.columns[1:-1])
X = ok_counties_2017[features]
preds = clf4.predict(X) 
itemindex = np.where(preds==True)
risky_counties = data2017.ix[itemindex]

In [154]:
risky_counties

County  Rural  Rehab_Count  EMS_COUNT  hospital_count  \
50  Effingham      0            1          1               1   
62      Glynn      0            1          2               2   
65     Greene      1            2          1               1   
69    Hancock      1            0          1               0   
72       Hart      1            1          1               0   
74      Henry      0            2          2               2   
91    Lowndes      0            4          1               2   
94    Madison      1            1          3               0   

    dropbox_247availability  dropbox_count    1yrlag    5yrlag   10yrlag  \
50                        0              1 -0.161214  0.258178  1.516357   
62                        1              1 -0.051033  0.328554  0.107129   
65                        0              1  0.325228  0.325228 -0.337386   
69                        0              0  0.000000  0.000000  0.000000   
72                        0              0 -0.180957 -0.590478 -0.180957   
74                        0              1 -0.034866  0.700475  1.746921   
91                        1              1 -0.073608  0.455760  2.396772   
94                        0              1  0.201827 -0.038539  3.807307   

          ...          ER_5yrlag  ER_10yrlag  drug_ER_Visits_2017  \
50        ...           3.762295    4.766749             0.002324   
62        ...           6.382682   11.645933             0.007929   
65        ...          18.520129   25.997773             0.012122   
69        ...           9.593248    9.593248             0.006589   
72        ...           0.252218    0.221061             0.001031   
74        ...           8.243346    5.752778             0.002431   
91        ...          11.632353   20.802030             0.004295   
94        ...           6.459054   16.621253             0.006467   

    teenage_pregnancy_2017  2017_children_poverty  2017_death_rate  \
50                0.010079               0.154739         0.007226   
62                0.015296               0.309685         0.010175   
65                0.010460               0.356946         0.012328   
69                0.028099               0.387093         0.015939   
72                0.019465               0.290110         0.011715   
74                0.005924               0.171629         0.007114   
91                0.012464               0.334000         0.007724   
94                0.019353               0.203358         0.008858   

    2017_birth_rate  2017_prescription  2017_ODRate  2017ODabovenatavg  
50         0.012946           0.767327     0.000083              False  
62         0.011457           1.039094     0.000155              False  
65         0.009546           1.466861     0.000077              False  
69         0.007573           0.540507     0.000012              False  
72         0.010176           1.004745     0.000064              False  
74         0.011643           0.750773     0.000158              False  
91         0.014248           0.891325     0.000089              False  
94         0.007361           0.779000     0.000337               True  

[8 rows x 42 columns]

In [155]:
features = list(ok_counties_2018.columns[1:-1])
X = ok_counties_2018[features]
preds = clf4.predict(X) 
itemindex = np.where(preds==True)
risky_counties = data2018.ix[itemindex]

In [156]:
risky_counties

County  Rural  Rehab_Count  EMS_COUNT  hospital_count  \
12   Brantley      1            0          1               0   
50  Effingham      0            1          1               1   
62      Glynn      0            1          2               2   
69    Hancock      1            0          1               0   
72       Hart      1            1          1               0   
74      Henry      0            2          2               2   
83      Jones      1            0          0               0   
88    Liberty      0            1          1               2   
91    Lowndes      0            4          1               2   
94    Madison      1            1          3               0   

    dropbox_247availability  dropbox_count    1yrlag    5yrlag   10yrlag  \
12                        0              1  0.049341  1.869142  4.738285   
50                        0              1  0.031957 -0.258065  0.731181   
62                        1              1  0.029622 -0.316046 -0.022922   
69                        0              0  0.000000  0.000000 -0.898986   
72                        0              0 -0.257793 -0.696050 -0.797367   
74                        0              1  0.049340  0.498876  0.703268   
83                        1              1 -0.138828 -0.301673  0.163878   
88                        1              1  0.012306 -0.193528 -0.032234   
91                        1              1  0.018963  1.076711  1.595889   
94                        0              1 -0.050908 -0.348203 -0.087484   

          ...          ER_5yrlag  ER_10yrlag  drug_ER_Visits_2018  \
12        ...           3.438105    7.052734             0.004123   
50        ...           4.403628    6.565079             0.002383   
62        ...          10.860132   11.005574             0.010769   
69        ...          14.231511   14.231511             0.009474   
72        ...           1.144829   -0.016151             0.001096   
74        ...           4.869668    7.042208             0.002477   
83        ...          15.926984   14.234286             0.005332   
88        ...          13.270463   14.725490             0.004010   
91        ...          13.837093   46.741935             0.005920   
94        ...           8.604526   16.790419             0.008913   

    teenage_pregnancy_2018  2018_children_poverty  2018_death_rate  \
12                0.027182               0.353183         0.010789   
50                0.010043               0.154453         0.007271   
62                0.013410               0.312769         0.010121   
69                0.029000               0.364671         0.017860   
72                0.018724               0.291664         0.012052   
74                0.005020               0.175545         0.007394   
83                0.008787               0.176521         0.009834   
88                0.019739               0.290209         0.005520   
91                0.011030               0.340000         0.007853   
94                0.018653               0.176589         0.008817   

    2018_birth_rate  2018_prescription  2018_ODRate  2018ODabovenatavg  
12         0.011099           0.469791     0.000306               True  
50         0.012826           0.735037     0.000084              False  
62         0.011186           1.042509     0.000158              False  
69         0.007364           0.536308     0.000012              False  
72         0.010010           0.978106     0.000047              False  
74         0.011448           0.715955     0.000163               True  
83         0.008511           0.564118     0.000122              False  
88         0.019229           0.515046     0.000078              False  
91         0.014441           0.855649     0.000090              False  
94         0.006732           0.806000     0.000315               True  

[10 rows x 42 columns]